#!/bin/bash
#
# generate_hash_vectors.sh
#
# Generates deterministic hash test vectors using the native build.
# These vectors are used to verify cross-platform hash consistency.
#
# Usage:
#   ./scripts/generate_hash_vectors.sh
#
# Output:
#   Prints Rust test vector definitions that can be pasted into tests/cross_platform_tests.rs
#   Also outputs JSON format for snapshot files
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Deterministic Hash Vector Generator ===${NC}"
echo ""

# Verify we're in the right directory
if [ ! -f "$PROJECT_ROOT/Cargo.toml" ]; then
    echo -e "${RED}Error: Cargo.toml not found. Are you in the project root?${NC}"
    exit 1
fi

# Build the native binary if not already built
if [ ! -f "$PROJECT_ROOT/target/debug/anchorkit" ]; then
    echo -e "${YELLOW}Building native binary...${NC}"
    cd "$PROJECT_ROOT"
    cargo build --release 2>&1 | grep -E "(Compiling|Finished|error)" || true
    echo ""
fi

# Create a temporary Rust program to generate the vectors
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

cat > "$TEMP_DIR/generate_vectors.rs" << 'EOF'
use sha2::{Sha256, Digest};

fn main() {
    // Define test vectors with known inputs
    let vectors = vec![
        (
            "minimal_payload",
            "0000000000000000000000000000000000000000000000000000000000000000",
            1_700_000_000u64,
            b"kyc_approved".to_vec(),
        ),
        (
            "longer_payload",
            "0000000000000000000000000000000000000000000000000000000000000001",
            1_700_000_001u64,
            b"payment_confirmed_with_extended_metadata".to_vec(),
        ),
        (
            "zero_timestamp",
            "0000000000000000000000000000000000000000000000000000000000000002",
            0u64,
            b"genesis_attestation".to_vec(),
        ),
        (
            "max_timestamp",
            "0000000000000000000000000000000000000000000000000000000000000003",
            u64::MAX,
            b"future_attestation".to_vec(),
        ),
        (
            "empty_payload",
            "0000000000000000000000000000000000000000000000000000000000000004",
            1_600_000_000u64,
            b"".to_vec(),
        ),
    ];

    println!("// Hardcoded test vectors for cross-platform hash verification");
    println!("// Generated by: scripts/generate_hash_vectors.sh");
    println!("// Reference platform: native");
    println!("");

    for (name, subject_xdr_hex, timestamp, data_payload) in vectors {
        // Construct the input: subject_xdr || timestamp_be8 || data
        let mut input = Vec::new();
        
        // Add subject XDR bytes (convert hex to bytes)
        for i in (0..subject_xdr_hex.len()).step_by(2) {
            let byte = u8::from_str_radix(&subject_xdr_hex[i..i+2], 16).unwrap();
            input.push(byte);
        }
        
        // Add timestamp as 8-byte big-endian
        input.extend_from_slice(&timestamp.to_be_bytes());
        
        // Add data payload
        input.extend_from_slice(&data_payload);
        
        // Compute SHA-256
        let mut hasher = Sha256::new();
        hasher.update(&input);
        let hash = hasher.finalize();
        let hash_hex = format!("{:x}", hash);
        
        // Output as Rust constant
        println!("pub const VECTOR_{}: HashTestVector = HashTestVector {{", name.to_uppercase());
        println!("    name: \"{}\",", name);
        println!("    subject_xdr_hex: \"{}\",", subject_xdr_hex);
        println!("    timestamp: {}u64,", timestamp);
        println!("    data_payload: b\"{}\",", 
                 String::from_utf8_lossy(&data_payload).escape_default());
        println!("    expected_hash: \"{}\",", hash_hex);
        println!("}};");
        println!("");
    }
}
EOF

# Check if sha2 crate is available, if not use openssl
if command -v rustc &> /dev/null; then
    echo -e "${YELLOW}Compiling vector generator...${NC}"
    
    # Try to compile with sha2 first
    if rustc --edition 2021 "$TEMP_DIR/generate_vectors.rs" -o "$TEMP_DIR/generate_vectors" 2>/dev/null; then
        echo -e "${GREEN}Running vector generator...${NC}"
        "$TEMP_DIR/generate_vectors"
    else
        # Fallback to using openssl
        echo -e "${YELLOW}Using openssl for hash computation...${NC}"
        generate_vectors_with_openssl
    fi
else
    echo -e "${RED}Error: rustc not found${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}Vector generation complete!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "1. Copy the Rust constants above into tests/cross_platform_tests.rs"
echo "2. Update test_snapshots/deterministic_hash_tests/test_cross_environment_determinism.1.json"
echo "3. Run: cargo test --test cross_platform_tests"
echo "4. Verify tests pass on both native and WASM targets"
echo ""

# Function to generate vectors using openssl
generate_vectors_with_openssl() {
    local vectors=(
        "minimal_payload:0000000000000000000000000000000000000000000000000000000000000000:1700000000:kyc_approved"
        "longer_payload:0000000000000000000000000000000000000000000000000000000000000001:1700000001:payment_confirmed_with_extended_metadata"
        "zero_timestamp:0000000000000000000000000000000000000000000000000000000000000002:0:genesis_attestation"
        "max_timestamp:0000000000000000000000000000000000000000000000000000000000000003:18446744073709551615:future_attestation"
        "empty_payload:0000000000000000000000000000000000000000000000000000000000000004:1600000000:"
    )
    
    for vector in "${vectors[@]}"; do
        IFS=':' read -r name subject_xdr timestamp data <<< "$vector"
        
        # Construct input
        local input_hex="$subject_xdr"
        
        # Add timestamp as 8-byte big-endian
        printf -v ts_be '%016x' "$timestamp"
        input_hex="${input_hex}${ts_be}"
        
        # Add data as hex
        if [ -n "$data" ]; then
            input_hex="${input_hex}$(echo -n "$data" | xxd -p)"
        fi
        
        # Compute SHA-256
        local hash=$(echo -n "$input_hex" | xxd -r -p | openssl dgst -sha256 -hex | awk '{print $2}')
        
        echo "pub const VECTOR_${name^^}: HashTestVector = HashTestVector {"
        echo "    name: \"$name\","
        echo "    subject_xdr_hex: \"$subject_xdr\","
        echo "    timestamp: ${timestamp}u64,"
        echo "    data_payload: b\"$data\","
        echo "    expected_hash: \"$hash\","
        echo "};"
        echo ""
    done
}
